ALTER PLUGGABLE DATABASE FPDBCLONE OPEN

show con_name
CREATE USER TESTACC IDENTIFIED BY TESTACC
select con_id, name from v$containers
select username, common, con id from cdb_users where con id=4|

CREATE ROLE CLONEROLE;
GRANT ALTER SESSION TO CLONEROLE;
GRANT CREATE PLUGGABLE DATABASE TO CLONEROLE;
GRANT CREATE SESSION TO CLONEROLE;
GRANT CREATE TABLE TO CLONEROLE;
GRANT CREATE TABLESPACE TO CLONEROLE;
GRANT ALTER USER TO CLONEROLE;
GRANT CREATE USER TO CLONEROLE;
GRANT ALTER TABLESPACE TO CLONEROLE;
GRANT DROP USER TO CLONEROLE;
GRANT DROP TABLESPACE TO CLONEROLE;
GRANT CLONEROLE TO TESTACC
ALTER USER TESTACC PROFILE NERF

SELECT * FROM v$database;
