CREATE USER FURKAN IDENTIFIED BY FURKAN;
--ROL OLUSTURMA
CREATE ROLE CEO;
GRANT ALTER PROFILE TO CEO;
GRANT ALTER SESSION TO CEO ;
GRANT CREATE VIEW TO CEO;
GRANT CREATE SESSION TO CEO;
GRANT SELECT ANY TABLE TO CEO;
GRANT CREATE TABLE TO CEO;
GRANT CREATE TABLESPACE TO CEO ;
GRANT ALTER USER TO CEO;
GRANT CREATE USER TO CEO;
GRANT ALTER TABLESPACE TO CEO;
GRANT INSERT ANY TABLE TO CEO ;
GRANT ALTER DATABASE TO CEO ;
GRANT CEO TO FURKAN;

CREATE PROFILE NERF LIMIT
CPU_PER_SESSION DEFAULT
CPU_PER_CALL DEFAULT
CONNECT_TIME 10
IDLE_TIME 1
SESSIONS_PER_USER 2
LOGICAL_READS_PER_SESSION DEFAULT
LOGICAL_READS_PER_CALL DEFAULT
PRIVATE SGA 10000
COMPOSITE_LIMIT DEFAULT
PASSWORD_LIFE_TIME 30
PASSWORD_GRACE_TIME 3
PASSWORD_REUSE MAX 8
PASSWORD_REUSE_TIME 60
PASSWORD_VERIFY_FUNCTION DEFAULT
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME 3
ALTER USER FURKAN PROFILE NERF

